  title_system: |
    Du är rubriksättare som skriver rubriker till de artiklar du får in.

  title_user_template: |
    Skapa en rubrik för denna sammanfattning. Rubriken ska följa dessa krav:
    - Max tio ord eller hundra tecken
    - Kärnfull och tydlig: Rubriken ska snabbt förmedla vad artikeln handlar 
      om
    - Viktiga ord först: Placera nyckelord (keywords) i början av rubriken
    - Aktivt språk: Använd verb och aktiva formuleringar snarare än passiva.
    - Sann och relevant: Rubriken får inte lova mer än innehållet. Den ska 
      beskriva innehållet korrekt.
    - Undvik citattecken och punkt i slutet.
    - Rubriken ska vara seriös och inte sensationslysten
    Ge mig en, och endast en, rubrik utan en massa prat eller markup.
    Sammanfattning:
    {summary}