daily_hybrid_news_tech_se:
  frequency: "daily"
  time: "01:18"
  categories: 
    - "Teknik"
  promptpackage: "daily_hybrid_news_cyber_tech_se"
daily_hybrid_cyber:
  frequency: "daily"
  time: "06:00"
  categories: 
    - "Cybersecurity"
    - "Dataskydd"
    - "Sårbarheter"
  promptpackage: "daily_hybrid_news_cyber_tech_se"
weekly_hybrid_news_tech_se:
  frequency: "weekly"
  day: "sun"
  time: "23:00"
  categories: 
    - "Nyheter"
    - "Teknik"
  promptpackage: "weekly_hybrid_news_cyber_tech_se"
weekly_hybrid_cyber:
  frequency: "weekly"
  day: "sun"
  time: "23:59"
  categories: 
    - "Cybersecurity"
    - "Dataskydd"
    - "Sårbarheter"
  promptpackage: "weekly_hybrid_news_cyber_tech_se"